---
version: '2.0'
instances:
  girder:
    image: "docker://dsarchive/dsa_common"
    name: girder
    # restart: unless-stopped
    volumes:
      - ./assetstore:/assetstore
      - ./girder.cfg:/etc/girder.cfg
      # Give access to huggingface cache
      - ${HF_HOME:-${HOME}/.cache/huggingface}:/data/huggingface:ro
    depends_on:
      - mongodb
    command:
      bash -c 'python provision.py --sample-data && girder serve'
  mongodb:
    image: "docker://mongo:latest"
    name: mongodb
    # restart: unless-stopped
    command: --nojournal
    volumes:
      - ./db:/data/db
      # Give access to huggingface cache
      - ${HF_HOME:-${HOME}/.cache/huggingface}:/data/huggingface:ro
