---
services:
  girder:
    image: dsarchive/dsa_minimal
    build: .
    restart: unless-stopped
    ports:
      - "${DSA_PORT:-8080}:8080"
    volumes:
      - assetstore:/assetstore
      # Give access to huggingface cache
      - ${HF_HOME:-${HOME}/.cache/huggingface}:/data/huggingface:ro
    depends_on:
      - mongodb
  mongodb:
    image: "mongo:latest"
    restart: unless-stopped
    volumes:
      - db:/data/db
      # Give access to huggingface cache
      - ${HF_HOME:-${HOME}/.cache/huggingface}:/data/huggingface:ro
volumes:
  assetstore:
  db:
  ${HF_HOME:-${HOME}/.cache/huggingface}:
